// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

function abbreviate(name) {
  var param = $$String.uppercase_ascii(name).match((/\b\w/g));
  if (param !== null) {
    return $$Array.fold_left((function (prim, prim$1) {
                  return prim + prim$1;
                }), "", param);
  } else {
    return "";
  }
}

exports.abbreviate = abbreviate;
/* No side effect */
