// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Minesweeper$Minesweeper = require("../src/Minesweeper.bs.js");

Jest.describe("Minesweeper", (function (param) {
        Jest.test("no rows", (function (param) {
                return Jest.Expect.toEqual(/* array */[], Jest.Expect.expect(Minesweeper$Minesweeper.annotate(/* array */[])));
              }));
        Jest.test("no columns", (function (param) {
                return Jest.Expect.toEqual(/* array */[""], Jest.Expect.expect(Minesweeper$Minesweeper.annotate(/* array */[""])));
              }));
        Jest.test("no mines", (function (param) {
                var input = /* array */[
                  "   ",
                  "   ",
                  "   "
                ];
                return Jest.Expect.toEqual(input, Jest.Expect.expect(Minesweeper$Minesweeper.annotate(input)));
              }));
        Jest.test("board with only mines", (function (param) {
                var input = /* array */[
                  "***",
                  "***",
                  "***"
                ];
                return Jest.Expect.toEqual(input, Jest.Expect.expect(Minesweeper$Minesweeper.annotate(input)));
              }));
        Jest.test("mine surrounded by spaces", (function (param) {
                var input = /* array */[
                  "   ",
                  " * ",
                  "   "
                ];
                var annot = /* array */[
                  "111",
                  "1*1",
                  "111"
                ];
                return Jest.Expect.toEqual(annot, Jest.Expect.expect(Minesweeper$Minesweeper.annotate(input)));
              }));
        Jest.test("space surrounded by mines", (function (param) {
                var input = /* array */[
                  "***",
                  "* *",
                  "***"
                ];
                var annot = /* array */[
                  "***",
                  "*8*",
                  "***"
                ];
                return Jest.Expect.toEqual(annot, Jest.Expect.expect(Minesweeper$Minesweeper.annotate(input)));
              }));
        Jest.test("horizontal line", (function (param) {
                return Jest.Expect.toEqual(/* array */["1*2*1"], Jest.Expect.expect(Minesweeper$Minesweeper.annotate(/* array */[" * * "])));
              }));
        Jest.test("vertical line", (function (param) {
                var input = /* array */[
                  " ",
                  "*",
                  " ",
                  "*",
                  " "
                ];
                var annot = /* array */[
                  "1",
                  "*",
                  "2",
                  "*",
                  "1"
                ];
                return Jest.Expect.toEqual(annot, Jest.Expect.expect(Minesweeper$Minesweeper.annotate(input)));
              }));
        Jest.test("vertical line, mine at edges", (function (param) {
                var input = /* array */[
                  "*",
                  " ",
                  " ",
                  " ",
                  "*"
                ];
                var annot = /* array */[
                  "*",
                  "1",
                  " ",
                  "1",
                  "*"
                ];
                return Jest.Expect.toEqual(annot, Jest.Expect.expect(Minesweeper$Minesweeper.annotate(input)));
              }));
        Jest.test("cross", (function (param) {
                var input = /* array */[
                  "  *  ",
                  "  *  ",
                  "*****",
                  "  *  ",
                  "  *  "
                ];
                var annot = /* array */[
                  " 2*2 ",
                  "25*52",
                  "*****",
                  "25*52",
                  " 2*2 "
                ];
                return Jest.Expect.toEqual(annot, Jest.Expect.expect(Minesweeper$Minesweeper.annotate(input)));
              }));
        return Jest.test("large board", (function (param) {
                      var input = /* array */[
                        " *  * ",
                        "  *   ",
                        "    * ",
                        "   * *",
                        " *  * ",
                        "      "
                      ];
                      var annot = /* array */[
                        "1*22*1",
                        "12*322",
                        " 123*2",
                        "112*4*",
                        "1*22*2",
                        "111111"
                      ];
                      return Jest.Expect.toEqual(annot, Jest.Expect.expect(Minesweeper$Minesweeper.annotate(input)));
                    }));
      }));

/*  Not a pure module */
