// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function isQuestion(sentence) {
  return (/\?$/).test(sentence);
}

function isYell(sentence) {
  return (/^[^a-z]*[A-Z][^a-z]*$/).test(sentence);
}

function isYellQuestion(sentence) {
  if (isQuestion(sentence)) {
    return isYell(sentence);
  } else {
    return false;
  }
}

function hey(say) {
  var str = $$String.trim(say);
  if (str === "") {
    return "Fine. Be that way!";
  } else if (isYellQuestion(str)) {
    return "Calm down, I know what I'm doing!";
  } else if (isQuestion(str)) {
    return "Sure.";
  } else if (isYell(str)) {
    return "Whoa, chill out!";
  } else {
    return "Whatever.";
  }
}

exports.isQuestion = isQuestion;
exports.isYell = isYell;
exports.isYellQuestion = isYellQuestion;
exports.hey = hey;
/* No side effect */
