// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function $percent$percent(x, y) {
  return Caml_int32.mod_(x, y) === 0;
}

function raindrops(number) {
  var result = $$String.concat("", List.map((function (param) {
              var number$1 = number;
              var param$1 = param;
              var match = $percent$percent(number$1, param$1[0]);
              if (match) {
                return param$1[1];
              } else {
                return "";
              }
            }), /* :: */[
            /* tuple */[
              3,
              "Pling"
            ],
            /* :: */[
              /* tuple */[
                5,
                "Plang"
              ],
              /* :: */[
                /* tuple */[
                  7,
                  "Plong"
                ],
                /* [] */0
              ]
            ]
          ]));
  if (result === "") {
    return String(number);
  } else {
    return result;
  }
}

exports.raindrops = raindrops;
/* No side effect */
