// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Char = require("bs-platform/lib/js/char.js");
var List = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");

function isPangram(sentence) {
  var s = $$String.lowercase_ascii(sentence).replace((/[^a-z]/g), "");
  return List.for_all((function (c) {
                return $$String.contains(s, Char.chr(c));
              }), List.init(26, (function (param) {
                    return /* "a" */97 + param | 0;
                  })));
}

exports.isPangram = isPangram;
/* No side effect */
