// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function is_isogram(word) {
  return !(/([a-z]).*\1/g).test($$String.lowercase_ascii(word).replace((/[^a-z]/g), ""));
}

exports.is_isogram = is_isogram;
/* No side effect */
