// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function ageOn(planet, sec) {
  switch (planet) {
    case /* Mercury */0 :
        return sec / (31557600.0 * 0.2408467);
    case /* Venus */1 :
        return sec / (31557600.0 * 0.61519726);
    case /* Earth */2 :
        return sec / (31557600.0 * 1.0);
    case /* Mars */3 :
        return sec / (31557600.0 * 1.8808158);
    case /* Jupiter */4 :
        return sec / (31557600.0 * 11.862615);
    case /* Saturn */5 :
        return sec / (31557600.0 * 29.447498);
    case /* Neptune */6 :
        return sec / (31557600.0 * 164.79132);
    case /* Uranus */7 :
        return sec / (31557600.0 * 84.016846);
    
  }
}

exports.ageOn = ageOn;
/* No side effect */
