// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function transToRna(nucleo) {
  switch (nucleo) {
    case /* A */0 :
        return /* U */3;
    case /* C */1 :
        return /* G */2;
    case /* G */2 :
        return /* C */1;
    case /* T */3 :
        return /* A */0;
    
  }
}

function toRna(param) {
  return List.map(transToRna, param);
}

exports.toRna = toRna;
/* No side effect */
