// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function splitInt(n) {
  if (n !== 0) {
    return /* :: */[
            n % 10,
            splitInt(n / 10 | 0)
          ];
  } else {
    return /* [] */0;
  }
}

function validate(number) {
  var len = String(number).length;
  return number === List.fold_left((function (prim, prim$1) {
                return prim + prim$1 | 0;
              }), 0, List.map((function (param) {
                    var exp = len;
                    var base = param;
                    return Math.pow(base, exp) | 0;
                  }), splitInt(number)));
}

exports.validate = validate;
/* No side effect */
