// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");

function count(dict, word) {
  var match = Js_dict.get(dict, word);
  if (match !== undefined) {
    dict[word] = match + 1 | 0;
  } else {
    dict[word] = 1;
  }
  return dict;
}

function wordCount(sentence) {
  return $$String.trim($$String.lowercase_ascii(sentence).replace((/[^a-z0-9' ]+| '|' /g), " ").replace((/ +/g), " ")).split(" ").reduce(count, { });
}

exports.wordCount = wordCount;
/* No side effect */
