// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Anagram$Anagram = require("../src/Anagram.bs.js");

Jest.describe("Anagram", (function (param) {
        Jest.test("no matches", (function (param) {
                return Jest.Expect.toEqual(/* [] */0, Jest.Expect.expect(Anagram$Anagram.anagrams("diaper", /* :: */[
                                    "hello",
                                    /* :: */[
                                      "world",
                                      /* :: */[
                                        "zombies",
                                        /* :: */[
                                          "pants",
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("detects two anagrams", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            "stream",
                            /* :: */[
                              "maters",
                              /* [] */0
                            ]
                          ], Jest.Expect.expect(Anagram$Anagram.anagrams("master", /* :: */[
                                    "stream",
                                    /* :: */[
                                      "pigeon",
                                      /* :: */[
                                        "maters",
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("does not detect anagram subsets", (function (param) {
                return Jest.Expect.toEqual(/* [] */0, Jest.Expect.expect(Anagram$Anagram.anagrams("good", /* :: */[
                                    "dog",
                                    /* :: */[
                                      "goody",
                                      /* [] */0
                                    ]
                                  ])));
              }));
        Jest.test("detects anagram", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            "inlets",
                            /* [] */0
                          ], Jest.Expect.expect(Anagram$Anagram.anagrams("listen", /* :: */[
                                    "enlists",
                                    /* :: */[
                                      "google",
                                      /* :: */[
                                        "inlets",
                                        /* :: */[
                                          "banana",
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("detects three anagrams", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            "gallery",
                            /* :: */[
                              "regally",
                              /* :: */[
                                "largely",
                                /* [] */0
                              ]
                            ]
                          ], Jest.Expect.expect(Anagram$Anagram.anagrams("allergy", /* :: */[
                                    "gallery",
                                    /* :: */[
                                      "ballerina",
                                      /* :: */[
                                        "regally",
                                        /* :: */[
                                          "clergy",
                                          /* :: */[
                                            "largely",
                                            /* :: */[
                                              "leading",
                                              /* [] */0
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("detects multiple anagrams with different case", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            "Eons",
                            /* :: */[
                              "ONES",
                              /* [] */0
                            ]
                          ], Jest.Expect.expect(Anagram$Anagram.anagrams("nose", /* :: */[
                                    "Eons",
                                    /* :: */[
                                      "ONES",
                                      /* [] */0
                                    ]
                                  ])));
              }));
        Jest.test("does not detect non-anagrams with identical checksum", (function (param) {
                return Jest.Expect.toEqual(/* [] */0, Jest.Expect.expect(Anagram$Anagram.anagrams("mass", /* :: */[
                                    "last",
                                    /* [] */0
                                  ])));
              }));
        Jest.test("detects anagrams case-insensitively", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            "Carthorse",
                            /* [] */0
                          ], Jest.Expect.expect(Anagram$Anagram.anagrams("Orchestra", /* :: */[
                                    "cashregister",
                                    /* :: */[
                                      "Carthorse",
                                      /* :: */[
                                        "radishes",
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("detects anagrams using case-insensitive subject", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            "carthorse",
                            /* [] */0
                          ], Jest.Expect.expect(Anagram$Anagram.anagrams("Orchestra", /* :: */[
                                    "cashregister",
                                    /* :: */[
                                      "carthorse",
                                      /* :: */[
                                        "radishes",
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("detects anagrams using case-insensitive possible matches", (function (param) {
                return Jest.Expect.toEqual(/* :: */[
                            "Carthorse",
                            /* [] */0
                          ], Jest.Expect.expect(Anagram$Anagram.anagrams("orchestra", /* :: */[
                                    "cashregister",
                                    /* :: */[
                                      "Carthorse",
                                      /* :: */[
                                        "radishes",
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        Jest.test("does not detect a anagram if the original word is repeated", (function (param) {
                return Jest.Expect.toEqual(/* [] */0, Jest.Expect.expect(Anagram$Anagram.anagrams("go", /* :: */[
                                    "go Go GO",
                                    /* [] */0
                                  ])));
              }));
        Jest.test("anagrams must use all letters exactly once", (function (param) {
                return Jest.Expect.toEqual(/* [] */0, Jest.Expect.expect(Anagram$Anagram.anagrams("tapper", /* :: */[
                                    "patter",
                                    /* [] */0
                                  ])));
              }));
        Jest.test("words are not anagrams of themselves (case-insensitive)", (function (param) {
                return Jest.Expect.toEqual(/* [] */0, Jest.Expect.expect(Anagram$Anagram.anagrams("BANANA", /* :: */[
                                    "BANANA",
                                    /* :: */[
                                      "Banana",
                                      /* :: */[
                                        "banana",
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        return Jest.test("words other than themselves can be anagrams", (function (param) {
                      return Jest.Expect.toEqual(/* :: */[
                                  "Silent",
                                  /* [] */0
                                ], Jest.Expect.expect(Anagram$Anagram.anagrams("LISTEN", /* :: */[
                                          "Listen",
                                          /* :: */[
                                            "Silent",
                                            /* :: */[
                                              "LISTEN",
                                              /* [] */0
                                            ]
                                          ]
                                        ])));
                    }));
      }));

/*  Not a pure module */
