// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function accumulate(f, param) {
  if (param) {
    return /* :: */[
            Curry._1(f, param[0]),
            accumulate(f, param[1])
          ];
  } else {
    return /* [] */0;
  }
}

exports.accumulate = accumulate;
/* No side effect */
