// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function filterBin(_n, _l) {
  while(true) {
    var l = _l;
    var n = _n;
    if (l) {
      var tail = l[1];
      var match = n % 2 === 1;
      if (match) {
        return /* :: */[
                l[0],
                filterBin(n / 2 | 0, tail)
              ];
      } else {
        _l = tail;
        _n = n / 2 | 0;
        continue ;
      }
    } else {
      return /* [] */0;
    }
  };
}

function toList(i) {
  return filterBin(i, /* :: */[
              "eggs",
              /* :: */[
                "peanuts",
                /* :: */[
                  "shellfish",
                  /* :: */[
                    "strawberries",
                    /* :: */[
                      "tomatoes",
                      /* :: */[
                        "chocolate",
                        /* :: */[
                          "pollen",
                          /* :: */[
                            "cats",
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

function isAllergicTo(str, i) {
  return List.mem(str, toList(i));
}

exports.filterBin = filterBin;
exports.isAllergicTo = isAllergicTo;
exports.toList = toList;
/* No side effect */
