// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var RunLengthEncoding$RunLengthEncoding = require("../src/RunLengthEncoding.bs.js");

Jest.describe("encode function", (function (param) {
        Jest.test("empty string", (function (param) {
                return Jest.Expect.toBe("", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.encode("")));
              }));
        Jest.test("single characters only are encoded without count", (function (param) {
                return Jest.Expect.toBe("XYZ", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.encode("XYZ")));
              }));
        Jest.test("string with no single characters", (function (param) {
                return Jest.Expect.toBe("2A3B4C", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.encode("AABBBCCCC")));
              }));
        Jest.test("single characters mixed with repeated characters", (function (param) {
                return Jest.Expect.toBe("12WB12W3B24WB", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.encode("WWWWWWWWWWWWBWWWWWWWWWWWWBBBWWWWWWWWWWWWWWWWWWWWWWWWB")));
              }));
        Jest.test("multiple whitespace mixed in string", (function (param) {
                return Jest.Expect.toBe("2 hs2q q2w2 ", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.encode("  hsqq qww  ")));
              }));
        return Jest.test("lowercase characters", (function (param) {
                      return Jest.Expect.toBe("2a3b4c", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.encode("aabbbcccc")));
                    }));
      }));

Jest.describe("decode function", (function (param) {
        Jest.test("empty string", (function (param) {
                return Jest.Expect.toBe("", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.decode("")));
              }));
        Jest.test("single characters only", (function (param) {
                return Jest.Expect.toBe("XYZ", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.decode("XYZ")));
              }));
        Jest.test("string with no single characters", (function (param) {
                return Jest.Expect.toBe("AABBBCCCC", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.decode("2A3B4C")));
              }));
        Jest.test("single characters with repeated characters", (function (param) {
                return Jest.Expect.toBe("WWWWWWWWWWWWBWWWWWWWWWWWWBBBWWWWWWWWWWWWWWWWWWWWWWWWB", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.decode("12WB12W3B24WB")));
              }));
        Jest.test("multiple whitespace mixed in string", (function (param) {
                return Jest.Expect.toBe("  hsqq qww  ", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.decode("2 hs2q q2w2 ")));
              }));
        return Jest.test("lower case string", (function (param) {
                      return Jest.Expect.toBe("aabbbcccc", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.decode("2a3b4c")));
                    }));
      }));

Jest.describe("Encode/decode are inverse operations", (function (param) {
        return Jest.test("encode(followed by decode gives original string", (function (param) {
                      return Jest.Expect.toBe("zzz ZZ  zZ", Jest.Expect.expect(RunLengthEncoding$RunLengthEncoding.decode(RunLengthEncoding$RunLengthEncoding.encode("zzz ZZ  zZ"))));
                    }));
      }));

/*  Not a pure module */
