// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function phoneNumber(nr) {
  return Belt_Option.map(Caml_option.null_to_opt(nr.replace((/[^0-9]/g), "").match((/^1?((?:[2-9][0-9]{2}){2}[0-9]{4})$/))), (function (r) {
                return Caml_array.caml_array_get(r, 1);
              }));
}

exports.phoneNumber = phoneNumber;
/* No side effect */
