// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Pangram$Pangram = require("../src/Pangram.bs.js");

Jest.describe("Pangram", (function (param) {
        Jest.test("sentence empty", (function (param) {
                return Jest.Expect.toEqual(false, Jest.Expect.expect(Pangram$Pangram.isPangram("")));
              }));
        Jest.test("recognizes a perfect lower case pangram", (function (param) {
                return Jest.Expect.toEqual(true, Jest.Expect.expect(Pangram$Pangram.isPangram("abcdefghijklmnopqrstuvwxyz")));
              }));
        Jest.test("pangram with only lower case", (function (param) {
                return Jest.Expect.toEqual(true, Jest.Expect.expect(Pangram$Pangram.isPangram("the quick brown fox jumps over the lazy dog")));
              }));
        Jest.test("missing character 'x'", (function (param) {
                return Jest.Expect.toEqual(false, Jest.Expect.expect(Pangram$Pangram.isPangram("a quick movement of the enemy will jeopardize five gunboats")));
              }));
        Jest.test("another missing character, e.g. 'h'", (function (param) {
                return Jest.Expect.toEqual(false, Jest.Expect.expect(Pangram$Pangram.isPangram("five boxing wizards jump quickly at it")));
              }));
        Jest.test("pangram with underscores", (function (param) {
                return Jest.Expect.toEqual(true, Jest.Expect.expect(Pangram$Pangram.isPangram("the_quick_brown_fox_jumps_over_the_lazy_dog")));
              }));
        Jest.test("pangram with numbers", (function (param) {
                return Jest.Expect.toEqual(true, Jest.Expect.expect(Pangram$Pangram.isPangram("the 1 quick brown fox jumps over the 2 lazy dogs")));
              }));
        Jest.test("missing letters replaced by numbers", (function (param) {
                return Jest.Expect.toEqual(false, Jest.Expect.expect(Pangram$Pangram.isPangram("7h3 qu1ck brown fox jumps ov3r 7h3 lazy dog")));
              }));
        Jest.test("pangram with mixed case and punctuation", (function (param) {
                return Jest.Expect.toEqual(true, Jest.Expect.expect(Pangram$Pangram.isPangram("\"Five quacking Zephyrs jolt my wax bed.\"")));
              }));
        return Jest.test("upper and lower case versions of the same character should not be counted separately", (function (param) {
                      return Jest.Expect.toEqual(false, Jest.Expect.expect(Pangram$Pangram.isPangram("the quick brown fox jumps over with lazy FX")));
                    }));
      }));

/*  Not a pure module */
