[package]
name = "primes"
version = "0.1.0"
authors = ["Thewessen <sthewessen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time-test = "0.2.2"
itertools = "0.9.0"
