// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function $percent$percent(x, y) {
  return Caml_int32.mod_(x, y) === 0;
}

function isLeapYear(year) {
  if ($percent$percent(year, 400) || !($percent$percent(year, 100) || !$percent$percent(year, 4))) {
    return true;
  } else {
    return false;
  }
}

exports.isLeapYear = isLeapYear;
/* No side effect */
