// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Allergies$Allergies = require("../src/Allergies.bs.js");

Jest.describe("Allergies", (function (param) {
        return Jest.describe("isAllergicTo", (function (param) {
                      Jest.describe("no Allergies means not allergic", (function (param) {
                              Jest.test("peanuts", (function (param) {
                                      return Jest.Expect.toBe(false, Jest.Expect.expect(Allergies$Allergies.isAllergicTo("peanuts", 0)));
                                    }));
                              Jest.test("cats", (function (param) {
                                      return Jest.Expect.toBe(false, Jest.Expect.expect(Allergies$Allergies.isAllergicTo("cats", 0)));
                                    }));
                              return Jest.test("strawberries", (function (param) {
                                            return Jest.Expect.toBe(false, Jest.Expect.expect(Allergies$Allergies.isAllergicTo("strawberries", 0)));
                                          }));
                            }));
                      Jest.test("is allergic to eggs", (function (param) {
                              return Jest.Expect.toBe(true, Jest.Expect.expect(Allergies$Allergies.isAllergicTo("eggs", 1)));
                            }));
                      Jest.describe("has the right allergies", (function (param) {
                              Jest.test("eggs", (function (param) {
                                      return Jest.Expect.toBe(true, Jest.Expect.expect(Allergies$Allergies.isAllergicTo("eggs", 5)));
                                    }));
                              Jest.test("shellfish", (function (param) {
                                      return Jest.Expect.toBe(true, Jest.Expect.expect(Allergies$Allergies.isAllergicTo("shellfish", 5)));
                                    }));
                              return Jest.test("strawberries", (function (param) {
                                            return Jest.Expect.toBe(false, Jest.Expect.expect(Allergies$Allergies.isAllergicTo("strawberries", 5)));
                                          }));
                            }));
                      return Jest.describe("toList", (function (param) {
                                    Jest.test("no allergies at all", (function (param) {
                                            return Jest.Expect.toEqual(/* [] */0, Jest.Expect.expect(Allergies$Allergies.toList(0)));
                                          }));
                                    Jest.test("allergic to just peanuts", (function (param) {
                                            return Jest.Expect.toEqual(/* :: */[
                                                        "peanuts",
                                                        /* [] */0
                                                      ], Jest.Expect.expect(Allergies$Allergies.toList(2)));
                                          }));
                                    Jest.test("allergic to everything", (function (param) {
                                            return Jest.Expect.toEqual(/* :: */[
                                                        "eggs",
                                                        /* :: */[
                                                          "peanuts",
                                                          /* :: */[
                                                            "shellfish",
                                                            /* :: */[
                                                              "strawberries",
                                                              /* :: */[
                                                                "tomatoes",
                                                                /* :: */[
                                                                  "chocolate",
                                                                  /* :: */[
                                                                    "pollen",
                                                                    /* :: */[
                                                                      "cats",
                                                                      /* [] */0
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ], Jest.Expect.expect(Allergies$Allergies.toList(255)));
                                          }));
                                    Jest.test("ignore non allergen score parts", (function (param) {
                                            return Jest.Expect.toEqual(/* :: */[
                                                        "eggs",
                                                        /* [] */0
                                                      ], Jest.Expect.expect(Allergies$Allergies.toList(257)));
                                          }));
                                    return Jest.test("ignore all non allergen score parts", (function (param) {
                                                  return Jest.Expect.toEqual(/* :: */[
                                                              "eggs",
                                                              /* :: */[
                                                                "shellfish",
                                                                /* :: */[
                                                                  "strawberries",
                                                                  /* :: */[
                                                                    "tomatoes",
                                                                    /* :: */[
                                                                      "chocolate",
                                                                      /* :: */[
                                                                        "pollen",
                                                                        /* :: */[
                                                                          "cats",
                                                                          /* [] */0
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ], Jest.Expect.expect(Allergies$Allergies.toList(509)));
                                                }));
                                  }));
                    }));
      }));

/*  Not a pure module */
