// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Isogram$Isogram = require("../src/Isogram.bs.js");

Jest.describe("Isograms", (function (param) {
        Jest.test("Empty string", (function (param) {
                return Jest.Expect.toBe(true, Jest.Expect.expect(Isogram$Isogram.is_isogram("")));
              }));
        Jest.test("Isogram with only lower case characters", (function (param) {
                return Jest.Expect.toBe(true, Jest.Expect.expect(Isogram$Isogram.is_isogram("isogram")));
              }));
        Jest.test("Word with one duplicated character", (function (param) {
                return Jest.Expect.toBe(false, Jest.Expect.expect(Isogram$Isogram.is_isogram("eleven")));
              }));
        Jest.test("Longest reported english isogram", (function (param) {
                return Jest.Expect.toBe(true, Jest.Expect.expect(Isogram$Isogram.is_isogram("subdermatoglyphic")));
              }));
        Jest.test("Word with duplicated character in mixed case", (function (param) {
                return Jest.Expect.toBe(false, Jest.Expect.expect(Isogram$Isogram.is_isogram("Alphabet")));
              }));
        Jest.test("Hypothetical isogrammic word with hyphen", (function (param) {
                return Jest.Expect.toBe(true, Jest.Expect.expect(Isogram$Isogram.is_isogram("thumbscrew-japingly")));
              }));
        Jest.test("Isogram with duplicated hyphen", (function (param) {
                return Jest.Expect.toBe(true, Jest.Expect.expect(Isogram$Isogram.is_isogram("six-year-old")));
              }));
        Jest.test("Made-up name that is an isogram", (function (param) {
                return Jest.Expect.toBe(true, Jest.Expect.expect(Isogram$Isogram.is_isogram("Emily Jung Schwartzkopf")));
              }));
        return Jest.test("Duplicated character in the middle", (function (param) {
                      return Jest.Expect.toBe(false, Jest.Expect.expect(Isogram$Isogram.is_isogram("accentor")));
                    }));
      }));

/*  Not a pure module */
