// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var SpaceAge$Spaceage = require("../src/SpaceAge.bs.js");

Jest.describe("Space Age", (function (param) {
        Jest.test("age on Earth", (function (param) {
                return Jest.Expect.toBeSoCloseTo(31.69, 2, Jest.Expect.expect(SpaceAge$Spaceage.ageOn(/* Earth */2, 1000000000.0)));
              }));
        Jest.test("age on Mercury", (function (param) {
                return Jest.Expect.toBeSoCloseTo(280.88, 2, Jest.Expect.expect(SpaceAge$Spaceage.ageOn(/* Mercury */0, 2134835688.0)));
              }));
        Jest.test("age on Venus", (function (param) {
                return Jest.Expect.toBeSoCloseTo(9.78, 2, Jest.Expect.expect(SpaceAge$Spaceage.ageOn(/* Venus */1, 189839836.0)));
              }));
        Jest.test("age on Mars", (function (param) {
                return Jest.Expect.toBeSoCloseTo(39.25, 2, Jest.Expect.expect(SpaceAge$Spaceage.ageOn(/* Mars */3, 2329871239.0)));
              }));
        Jest.test("age on Jupiter", (function (param) {
                return Jest.Expect.toBeSoCloseTo(2.41, 2, Jest.Expect.expect(SpaceAge$Spaceage.ageOn(/* Jupiter */4, 901876382.0)));
              }));
        Jest.test("age on Saturn", (function (param) {
                return Jest.Expect.toBeSoCloseTo(3.23, 2, Jest.Expect.expect(SpaceAge$Spaceage.ageOn(/* Saturn */5, 3000000000.0)));
              }));
        Jest.test("age on Uranus", (function (param) {
                return Jest.Expect.toBeSoCloseTo(1.21, 2, Jest.Expect.expect(SpaceAge$Spaceage.ageOn(/* Uranus */7, 3210123456.0)));
              }));
        return Jest.test("age on Neptune", (function (param) {
                      return Jest.Expect.toBeSoCloseTo(1.58, 2, Jest.Expect.expect(SpaceAge$Spaceage.ageOn(/* Neptune */6, 8210123456.0)));
                    }));
      }));

/*  Not a pure module */
