// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function twoFer(name) {
  var you = name !== undefined ? name : "you";
  return "One for " + (String(you) + ", one for me.");
}

exports.twoFer = twoFer;
/* No side effect */
