// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function repeat(str, n) {
  return $$String.concat("", $$Array.to_list(Caml_array.caml_make_vect(n, str)));
}

function getResult(dict, n) {
  if (dict) {
    var match = dict[0];
    var arabic = match[1];
    return repeat(match[0], Caml_int32.div(n, arabic)) + getResult(dict[1], Caml_int32.mod_(n, arabic));
  } else {
    return "";
  }
}

function toRoman(param) {
  return getResult(/* :: */[
              /* tuple */[
                "M",
                1000
              ],
              /* :: */[
                /* tuple */[
                  "CM",
                  900
                ],
                /* :: */[
                  /* tuple */[
                    "D",
                    500
                  ],
                  /* :: */[
                    /* tuple */[
                      "CD",
                      400
                    ],
                    /* :: */[
                      /* tuple */[
                        "C",
                        100
                      ],
                      /* :: */[
                        /* tuple */[
                          "XC",
                          90
                        ],
                        /* :: */[
                          /* tuple */[
                            "L",
                            50
                          ],
                          /* :: */[
                            /* tuple */[
                              "XL",
                              40
                            ],
                            /* :: */[
                              /* tuple */[
                                "X",
                                10
                              ],
                              /* :: */[
                                /* tuple */[
                                  "IX",
                                  9
                                ],
                                /* :: */[
                                  /* tuple */[
                                    "V",
                                    5
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      "IV",
                                      4
                                    ],
                                    /* :: */[
                                      /* tuple */[
                                        "I",
                                        1
                                      ],
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ], param);
}

exports.toRoman = toRoman;
exports.getResult = getResult;
exports.repeat = repeat;
/* No side effect */
